language: ruby

branches:
  except:
    - images

rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5.0
  - gemfiles/Gemfile.rails-4.2

env:
  - AN_ORM=active_record
  - AN_ORM=mongoid

matrix:
  exclude:
    - rvm: 2.1.9
      gemfile: gemfiles/Gemfile.rails-5.0
    - rvm: 2.1.9
      gemfile: Gemfile
    - env: AN_ORM=mongoid
      gemfile: Gemfile
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

services:
  - mongodb

sudo: false

cache: bundler

before_install: "rm ${BUNDLE_GEMFILE}.lock"

before_script: "bundle update"

script: bundle exec rspec

notifications:
  email: true 
